// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5JXNdMR9mhpW7_312FXB57mQhFPTrqNM',
    appId: '1:386713600488:web:b4cfe3f8dda91f6a87a45d',
    messagingSenderId: '386713600488',
    projectId: 'yahoooo',
    authDomain: 'oo-ef2e9.firebaseapp.com',
    storageBucket: 'yahoooo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdZMtw0w3xYorrH8EVnaIEULK6mKr6xCg',
    appId: '1:386713600488:android:05f4fce33196417d87a45d',
    messagingSenderId: '386713600488',
    projectId: 'yahoooo',
    storageBucket: 'yahoooo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkSLTQiOUOPrVbm7y6FiI_V1eHDtDdidE',
    appId: '1:386713600488:ios:ae4a9a80312c908f87a45d',
    messagingSenderId: '386713600488',
    projectId: 'yahoooo',
    storageBucket: 'yahoooo.appspot.com',
    iosBundleId: 'com.example.studio13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkSLTQiOUOPrVbm7y6FiI_V1eHDtDdidE',
    appId: '1:386713600488:ios:797fc6da5e8508b387a45d',
    messagingSenderId: '386713600488',
    projectId: 'yahoooo',
    storageBucket: 'yahoooo.appspot.com',
    iosBundleId: 'com.example.studio13.RunnerTests',
  );
}
